#!/usr/bin/php
<?php

require_once('../config.php');

$host = get_dbhost($hosts);
$sag = new Sag($host, $dbport);
$myip4 = get_ip(4);
$del = '='; /* set a delimiter to strip key and value */

$types['tqp500'] = array('fam' => 'kx', 'keys'=>'0', 'ekeys' => '0');
$types['t21p'] = array('fam' => 'kx', 'keys'=>'0', 'ekeys' => '0');

foreach($types as $mod => $val) {

    $prov['endpoint_brand'] = 'panasonic';
    $prov['endpoint_family'] = $val['fam'];
    $prov['endpoint_model'] = $mod;
    /* this is programable keys on phone */
    $prov['usr_keys']['setable_phone_keys'] = $val['keys'];
    $prov['usr_keys']['setable_phone_key_counter'] = '0';
    $prov['usr_keys']['setable_phone_key_value'] = 'fkey';
    /* this is extensions module keys */
    $prov['usr_keys']['setable_module_keys'] = $val['ekeys'];
    $prov['usr_keys']['setable_module_key_counter'] = '0';
    /* there use an special key for extensionsmodule */
    $prov['usr_keys']['setable_module_key_value'] = 'extkey';



// this is example manual plain to jaon format (ACCOUNT MUST BE!)
$in = 
'
PHONE_NUMBER_{ACCOUNT}="{SIPCALLERID}"
SIP_URI_{ACCOUNT}=""
LINE_ENABLE_{ACCOUNT}="Enabled"
PROFILE_ENABLE1="Enabled"
SIP_AUTHID_{ACCOUNT}="{SIPAUTHNAME}"
SIP_PASS_{ACCOUNT}="{SIPSECRET}"
SIP_SRC_PORT_{ACCOUNT}="5060"
SIP_PRXY_ADDR_{ACCOUNT}="{PROXY_SERVER}"
SIP_PRXY_PORT_{ACCOUNT}="5060"
SIP_RGSTR_ADDR_{ACCOUNT}="{PROXY_PORT}"
SIP_RGSTR_PORT_{ACCOUNT}="5060"
SIP_SVCDOMAIN_{ACCOUNT}=""
REG_EXPIRE_TIME_{ACCOUNT}="3600"
REG_INTERVAL_RATE_{ACCOUNT}="{PHONE_REREGISTER}"
SIP_SESSION_TIME_{ACCOUNT}="0"
SIP_SESSION_METHOD_{ACCOUNT}="0"
DSCP_SIP_{ACCOUNT}="0"
SIP_1NDPROXY_ADDR_{ACCOUNT}=""
SIP_1NDPROXY_PORT_{ACCOUNT}="5060"
SIP_2NDPROXY_ADDR_{ACCOUNT}=""
SIP_2NDPROXY_PORT_{ACCOUNT}="5060"
SIP_TIMER_T1_{ACCOUNT}="500"
SIP_TIMER_T2_{ACCOUNT}="4"
SIP_TIMER_T4_{ACCOUNT}="0"
SIP_FOVR_NORSP_{ACCOUNT}="Y"
SIP_FOVR_MAX_{ACCOUNT}="4"
SIP_REFRESHER_{ACCOUNT}="0"
SIP_DNSSRV_ENA_{ACCOUNT}="Y"
SIP_UDP_SRV_PREFIX_{ACCOUNT}="_sip._udp."
SIP_TCP_SRV_PREFIX_{ACCOUNT}="_sip._tcp."
SIP_{ACCOUNT}00REL_ENABLE_{ACCOUNT}="N"
SIP_INVITE_EXPIRE_{ACCOUNT}="0"
SIP_{ACCOUNT}8X_RTX_INTVL_{ACCOUNT}="0"
SIP_PRSNC_ADDR_{ACCOUNT}=""
SIP_PRSNC_PORT_{ACCOUNT}="5060"
SIP_2NDPRSNC_ADDR_{ACCOUNT}=""
SIP_2NDPRSNC_PORT_{ACCOUNT}="5060"
USE_DEL_REG_OPEN_{ACCOUNT}="N"
USE_DEL_REG_CLOSE_{ACCOUNT}="N"
PORT_PUNCH_INTVL_{ACCOUNT}="0"
SIP_REQURI_PORT_{ACCOUNT}="Y"
SIP_ADD_RPORT_{ACCOUNT}="N"
SIP_SUBS_EXPIRE_{ACCOUNT}="3600"
SUB_RTX_INTVL_{ACCOUNT}="10"
REG_RTX_INTVL_{ACCOUNT}="10"
SIP_P_PREFERRED_ID_{ACCOUNT}="N"
SIP_PRIVACY_{ACCOUNT}="N"
ADD_USER_PHONE_{ACCOUNT}="N"
SDP_USER_ID_{ACCOUNT}="-"
SUB_INTERVAL_RATE_{ACCOUNT}="90"
SIP_OUTPROXY_ADDR_{ACCOUNT}=""
SIP_OUTPROXY_PORT_{ACCOUNT}="5060"
SIP_TRANSPORT_{ACCOUNT}="0"
SIP_ANM_DISPNAME_{ACCOUNT}="1"
SIP_ANM_USERNAME_{ACCOUNT}="0"
SIP_ANM_HOSTNAME_{ACCOUNT}="N"
SIP_DETECT_SSAF_{ACCOUNT}="N"
SIP_RCV_DET_HEADER_{ACCOUNT}="N"
SIP_CONTACT_ON_ACK_{ACCOUNT}="N"
SIP_TIMER_B_{ACCOUNT}="32000"
SIP_TIMER_D_{ACCOUNT}="5000"
SIP_TIMER_F_{ACCOUNT}="32000"
SIP_TIMER_H_{ACCOUNT}="32000"
SIP_TIMER_J_{ACCOUNT}="5000"
ADD_TRANSPORT_UDP_{ACCOUNT}="N"
ADD_EXPIRES_HEADER_{ACCOUNT}="Y"
SIP_HOLD_HOLDRECEIVE_{ACCOUNT}="Y"
SIP_ADD_DIVERSION_{ACCOUNT}="1"

CODEC_ENABLE0_{ACCOUNT}="Y"
CODEC_ENABLE1_{ACCOUNT}="Y"
CODEC_ENABLE2_{ACCOUNT}="Y"
CODEC_ENABLE3_{ACCOUNT}="Y"
CODEC_ENABLE4_{ACCOUNT}="Y"
CODEC_PRIORITY0_{ACCOUNT}="1"
CODEC_PRIORITY1_{ACCOUNT}="1"
CODEC_PRIORITY2_{ACCOUNT}="1"
CODEC_PRIORITY3_{ACCOUNT}="1"
CODEC_PRIORITY4_{ACCOUNT}="1"
DSCP_RTP_{ACCOUNT}="0"
DSCP_RTCP_{ACCOUNT}="0"
RTCP_INTVL_{ACCOUNT}="5"
MAX_DELAY_{ACCOUNT}="20"
MIN_DELAY_{ACCOUNT}="2"
NOM_DELAY_{ACCOUNT}="2"
RTCP_ENABLE_{ACCOUNT}="N"
RTCP_SEND_BY_SDP_{ACCOUNT}="0"
RTP_CLOSE_ENABLE_{ACCOUNT}="Y"
OUTBANDDTMF_{ACCOUNT}="Y"
DTMF_RELAY_{ACCOUNT}="N"
RFC2543_HOLD_ENABLE_{ACCOUNT}="Y"

DISPLAY_NAME_{ACCOUNT}="{SIPCALLERID}"
VM_NUMBER_{ACCOUNT}="{VMSD}"
DIAL_PLAN_{ACCOUNT}="<:00>0[2-9]xxxxxxxxS0|<:0>0[2-9]xxxxxxxxS0"
DIAL_PLAN_NOT_MATCH_ENABLE_{ACCOUNT}="N"
SHARED_CALL_ENABLE_{ACCOUNT}="N"
FWD_DND_SYNCHRO_ENABLE_{ACCOUNT}="N"
RESOURCELIST_URI_{ACCOUNT}=""
CW_ENABLE_{ACCOUNT}="Y"
HOLD_SOUND_PATH_{ACCOUNT}="0"
';

$prov['cfg_account'] = json_decode(plain2json($in, $del)); /* ":" is for split line in 2 pices on : */

// this is example manual plain to jaon format (BASE OPTIONAL)
$in = 
'
ADMIN_ID="admin"
ADMIN_PASS="{PROVPASSWORD}"
USER_ID="user"
USER_PASS=""

TIME_ZONE="{TIMEZONE}"
DST_ENABLE="N"
DST_OFFSET="60"
DST_START_MONTH="3"
DST_START_ORDINAL_DAY="2"
DST_START_DAY_OF_WEEK="1"
DST_START_TIME="120"
DST_STOP_MONTH="10"
DST_STOP_ORDINAL_DAY="2"
DST_STOP_DAY_OF_WEEK="1"
DST_STOP_TIME="120"
LOCAL_TIME_ZONE_POSIX=""

SYSLOG_ADDR=""
SYSLOG_PORT="514"
SYSLOG_EVENT_SIP="0"
SYSLOG_EVENT_CFG="0"
SYSLOG_EVENT_VOIP="0"
SYSLOG_EVENT_TEL="0"
SYSLOG_RTPSMLY_INTVL_1="20"
SYSLOG_RTPSMLY_INTVL_2="20"
SYSLOG_RTPSMLY_INTVL_3="20"
SYSLOG_RTPSMLY_INTVL_4="20"

FIRM_UPGRADE_ENABLE="Y"
FIRM_VERSION="01.000"
FIRM_UPGRADE_AUTO="Y"
FIRM_FILE_PATH="http://{HOST_PROVSERVER}/prov/panasonic/fw/{MODEL}.fw"

OPTION66_ENABLE="Y"
OPTION66_REBOOT="N"
PROVISION_ENABLE="Y"
CFG_STANDARD_FILE_PATH="http://{HOST_PROVSERVER}/Config{mac}.cfg"
CFG_PRODUCT_FILE_PATH=""
CFG_MASTER_FILE_PATH="http://{HOST_PROVSERVER}/ConfigCommon.cfg"
CFG_FILE_KEY2=""
CFG_FILE_KEY3=""
CFG_FILE_KEY_LENGTH="128"
CFG_CYCLIC="N"
CFG_CYCLIC_INTVL="10080"
CFG_RTRY_INTVL="30"
CFG_RESYNC_TIME=""
CFG_RESYNC_FROM_SIP="check-sync"

ACS_URL=""
ACS_USER_ID=""
ACS_PASS=""
PERIODIC_INFORM_ENABLE="N"
PERIODIC_INFORM_INTERVAL="86400"
PERIODIC_INFORM_TIME="0001-01-01T00:00:00Z"
CON_REQ_USER_ID=""
CON_REQ_PASS=""
ANNEX_G_STUN_ENABLE="N"
ANNEX_G_STUN_SERV_ADDR=""
ANNEX_G_STUN_SERV_PORT="3478"
ANNEX_G_STUN_USER_ID=""
ANNEX_G_STUN_PASS=""
ANNEX_G_STUN_MAX_KEEP_ALIVE="300"
ANNEX_G_STUN_MIN_KEEP_ALIVE="30"
UDP_CON_REQ_ADDR_NOTIFY_LIMIT="0"

';

$prov['cfg_base'] = json_decode(plain2json($in, $del)); /* ":" is for split line in 2 pices on : */


// this is example manual plain to jaon format (BASE OPTIONAL)
$in =  /* putin behavior settings from phone  !!!!!!!*/
'
VM_SUBSCRIBE_ENABLE="N"
CONFERENCE_SERVER_URI="conference@example.com"
FIRSTDIGIT_TIM="30"
INTDIGIT_TIM="5"
MACRODIGIT_TIM="5"
INTERNATIONAL_ACCESS_CODE=""
COUNTRY_CALLING_CODE=""
NATIONAL_ACCESS_CODE=""
DEFAULT_LINE_SELECT="1"
DATA_LINE_MODE="N"
NUM_PLAN_PICKUP_DIRECT=""
TALK_PACKAGE="N"
HOLD_PACKAGE="N"
HOLD_RECALL_TIM="60"
AUTO_ANS_RING_TIM="5"
RINGING_OFF_SETTING_ENABLE="Y"
AUTO_CALL_HOLD="N"
REDIALKEY_CALLLOG_ENABLE="N"
ONHOOK_TRANSFER_ENABLE="Y"
DISCONNECTION_MODE="1"
TONE_LEN_DISCONNECT_HANDSET="10"
TONE_LEN_DISCONNECT_HANDSFREE="3"
KEY_PAD_TONE="Y"

XML_HTTPD_PORT="6666"
XMLAPP_ENABLE="N"
XMLAPP_USERID=""
XMLAPP_USERPASS=""
XMLAPP_START_URL=""
XMLAPP_INITIAL_URL=""
XMLAPP_INCOMING_URL=""
XMLAPP_TALKING_URL=""
XMLAPP_MAKECALL_URL=""
XMLAPP_CALLLOG_URL=""
XMLAPP_IDLING_URL=""
XMLAPP_LDAP_URL=""
XMLAPP_LDAP_USERID=""
XMLAPP_LDAP_USERPASS=""

';

$prov['cfg_behavior'] = json_decode(plain2json($in, $del));


// this is example manual plain to jaon format (BASE OPTIONAL)
$in =   /* putin behavior settings from phone  !!!!!!!!!*/
'
DIAL_TONE1_FRQ="350,440"
DIAL_TONE1_GAIN="0"
DIAL_TONE1_RPT="0"
DIAL_TONE1_TIMING="60,0"
DIAL_TONE2_FRQ="350,440"
DIAL_TONE2_GAIN="0"
DIAL_TONE2_RPT="0"
DIAL_TONE2_TIMING="60,0"
DIAL_TONE4_FRQ="350,440"
DIAL_TONE4_GAIN="0"
DIAL_TONE4_RPT="0"
DIAL_TONE4_TIMING="560,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,100,0"
BUSY_TONE_FRQ="480,620"
BUSY_TONE_GAIN="0"
BUSY_TONE_RPT="1"
BUSY_TONE_TIMING="60,500,440"
REORDER_TONE_FRQ="480,620"
REORDER_TONE_GAIN="0"
REORDER_TONE_RPT="1"
REORDER_TONE_TIMING="60,250,190"
RINGBACK_TONE_FRQ="440,480"
RINGBACK_TONE_GAIN="0"
RINGBACK_TONE_RPT="1"
RINGBACK_TONE_TIMING="60,2000,3940"
HOLD_ALARM_FRQ="425"
HOLD_ALARM_GAIN="0"
HOLD_ALARM_RPT="1"
HOLD_ALARM_TIMING="120,14880"
CW_TONE1_FRQ="425"
CW_TONE1_GAIN="0"
CW_TONE1_RPT="1"
CW_TONE1_TIMING="120,120,120,120,120,14400"
HOLD_TONE_FRQ="425"
HOLD_TONE_GAIN="0"
HOLD_TONE_RPT="1"
HOLD_TONE_TIMING="500,190,190,190,2890"
BELL_CORE_PATTERN1_TIMING="2000,4000"
BELL_CORE_PATTERN2_TIMING="800,400,800,4000"
BELL_CORE_PATTERN3_TIMING="400,200,400,200,800,4000"
BELL_CORE_PATTERN4_TIMING="300,200,1000,200,300,4000"
BELL_CORE_PATTERN5_TIMING="500"
';

$prov['cfg_tone'] = json_decode(plain2json($in, $del));

// this is example manual plain to jaon format (BASE OPTIONAL)
$in =   /* putin behavior settings from phone  !!!!!!!!!!*/
'

';

$prov['cfg_key'] = json_decode(plain2json($in, $del));

$prov['pvt_generator'] = 'json2plain';
$prov['pvt_counter'] = 1;
$prov['pvt_type'] = 'provisioner';
echo upload_phone_data($prov);
unset($prov);
}

?>